CREATE TABLEE [IF NOT EXISTS] [sqlite_schema].SCHEDULEDFEEDS (
	FEED_ID INTEGER PRIMARY KEY,
	TIME TEXT DEFAULT NULL
);
INSERT INTO SCHEDULEDFEEDS(FEED_ID,TIME) VALUES(1,NULL);
INSERT INTO SCHEDULEDFEEDS(FEED_ID,TIME) VALUES(2,NULL);
INSERT INTO SCHEDULEDFEEDS(FEED_ID,TIME) VALUES(3,NULL);